### ISSUE TITLE
Is it possible to sort solution according to the objective evaluation?

### ISSUE THREAD

**Issue by Antonio-Nappi** [jMetal/jMetalPy#98]
Hi everyone, when I obtain a Pareto front, I'm interested not in all solutions but in the solution that has minimum value in all the objective functions. How can I obtain this solution?
![api_algorithm_multiobjective_psos_omopso_5_0](https://user-images.githubusercontent.com/44395280/104492109-77b8eb00-55d3-11eb-9f11-d31934b86dff.png)
(According to the figure, I want the red dot)

**Comment by sebhan2** [comment]
Hi, you can just use a single objective function and formulate it as the sum of your two original objectives. As long as your original two objective problems pareto set is convex this gives you the solution you are looking for. If the pareto front to your problem is concave or your solution is in a concave region of the pareto front you can not find the solution by a single weighted sum objective. Hope this is helpful.
